id: 09d7be513a204f228970ec3bf1735d56
initial_creation_type: ocr
source_metadata:
  volumes:
    d8da5ecfe52e4651ac969427b23efaa4:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ཀླུ་སྒྲུབ་ཀྱི་གླུ།
      total_pages: 1953
      volume_number: 27
